spring:
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:navbatuz.c7e48wqu82el.eu-central-1.rds.amazonaws.com}:${DB_PORT:5432}/${DB_NAME:navbatuz}?sslmode=require
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Fatkh7267(?)}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 5000

logging:
  file:
    name: logs/app.log
  level:
    root: INFO

app:
  jwt:
    secret: 7267
    expirationMs: 86400000
  uploads:
    dir: uploads