spring:
  config:
    import: optional:env[.env]

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  file:
    name: logs/app.log
  level:
    root: INFO

app:
  jwt:
    secret: 7267
    expirationMs: 86400000

  uploads:
    # directory on disk (can be absolute or relative to app working dir)
    dir: uploads
    # base public URL for generating returned URLs
    base-url: http://localhost:8080

