spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/navbatuz
    username: postgres
    password: asdf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
server:
  port: 8080
